### PR TITLE
fixes for note spawn timing

### PR DESCRIPTION
**Pull request by TripleDaylinq**
Here's the fix as promised. I don't know if the timings are completely accurate, but without implementing any ms or beat based timings, this should at least be better across most songs.
I've also added a small fix on the scoring calc, because there was a problem where if you had a 95%, 90%, 80%, 70% or 60% exactly, you would get an F.

Good luck with your current project and have a nice day.

### CODE REVIEW

**Comment by TripleDaylinq** [comment]
actually, you might want to adjust the timings a bit. im getting almost all greats on an easy song. (this was already kinda the case in the original, but it feels like I somehow made the hit timings tighter and I dont remember doing that.)

**Comment by koneko** [comment]
hit timings are hard coded, unless you change that it speed should have no
effect

**Comment by TripleDaylinq** [comment]
at press(key):
let different = Math.abs(arrow.calcY())

different is how high the arrow is compared to the receptor at the time of pressing the key.
because a movement step of an arrow happens each frame, the arrow might be within the Marvelous rating one frame and outside of it the next. This is amplified by the speed of the arrow, because it will make larger movement steps, therefore there is less time the arrow is actually in any rating zone. It could even skip ratings entirely. But realistically that shouldn't matter, because I set the speed to be exactly what it was before. (2.5 * speed and speed was always 10, so I set it to 25)

**Comment by TripleDaylinq** [comment]
A better way to time (in my opinion, I am by no means an expert) would be to compare the millisecond timing of the note to the milisecond timing at wich you press a key. I've already implemented this in what im working on an it solves this problem, but idk what you wanna do. I understand if you just want to focus on your C# remake, so I won't bother you with anything else.

**Comment by koneko** [comment]
yes, that is a smart idea, and im planning on implementing it, however i
made this as a first project when working with pixi.js so i figured this
was easier to implement. thanks for this, love talking about this with
someone :)

**Pull request merged**
